### PR TITLE
Track visitor logs for analysis

### PR DESCRIPTION
**Pull request by thefinn93**
Just wanna hear people's thoughts on this before merging. I change the URL to analytics.hyperboria.net or something if people would prefer.

### CODE REVIEW

**Comment by dansup** [comment]
I think this is a good idea, as Piwik does offer opt-out for privacy minded folks.

**Comment by ghost** [comment]
Go for it

**Comment by lukevers** [comment]
:+1:

**Comment by thefinn93** [comment]
Okay, I'm merging this.

**Pull request merged**
